# Generated by Django 5.1.4 on 2025-01-07 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulkupload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UsersModel',
        ),
    ]
